name: Check linter & formatting

on:
  workflow_call:

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.1.0"

      - name: Install Dependencies
        run: npm ci

      - name: Code format
        run: npm run format

      - name: Lint code
        run: npm run lint
